name: Static Code Analysis

on: [push, pull_request]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Change directory to server folder
        run: cd server  # Replace 'server' with the actual directory name

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js